version: "3.5"

networks:
  inception:
    name: inception

volumes:
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      device: /home/cjad/data/wordpress
      o: bind


  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      device: /home/cjad/data/mariadb
      o: bind

services:
  nginx:
    image: nginx
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    restart: always


  wordpress:
    image: wordpress
    build: ./requirements/wordpress/
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    restart: always

  mariadb:
    image: mariadb
    build: ./requirements/mariadb/
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysqla
    restart: always
  ftp:
    container_name: ftp
    image: ftp
    build: ./requirements/bonus/ftp
    env_file:
      - .env
    depends_on:
      - wordpress
    volumes:
      - wordpress:/home/cjad/ftp/fi
    networks:
      - inception
    ports:
      - "21:21"
      - "40000-40005:40000-40005"
    restart: always
  cadvisor:
    container_name: cadvisor
    image: cadvisor
    build: ./requirements/bonus/cadvisor
    networks:
      - inception
    ports:
      - "8080:8080"
