CREATE DATABASE IF NOT EXISTS cjad_db ;
CREATE USER IF NOT EXISTS 'cjad'@'%' IDENTIFIED BY 'jad' ;
GRANT ALL PRIVILEGES ON cjad_db.* TO 'cjad'@'%' ;
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '12345' ;